name: Scheduled Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '30 3 * * *'

jobs:
  schedule:
    runs-on: ubuntu-latest

    steps:
    - name: Run Update Checker
      run: |
        chmod +x jb.sh
        jb.sh
