name: Scheduled Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '30 3 * * *'

jobs:
  schedule:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main
      
    - name: Run Update Checker
      run:  ls -a && chmod +x ./jb.sh && ./jb.sh
      env:
        token: ${{ secrets.TOKEN }}
