name: Scheduled Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '30 3 * * *'

env:
  JB_SH: jb.sh

jobs:
  schedule:
    runs-on: ubuntu-latest

    steps:
    - name: Run Update Checker
      run: chmod +x ${JB_SH} && ${JB_SH}
