name: Scheduled Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '30 3 * * *'

env:
  JB_SH: jb.sh

jobs:
  schedule:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main
      
    - name: Run Update Checker
      run: ls -a ${GITHUB_WORKSPACE} && chmod +x ${GITHUB_WORKSPACE}/${JB_SH} && ${GITHUB_WORKSPACE}/${JB_SH}
