name: Scheduled Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '30 3 * * *'

jobs:
  schedule:
    runs-on: ubuntu-latest

    steps:
      - name: Run Update Checker
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            const { Octokit } = require('@octokit/core');

            async function run() {
              const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });
              
              const source_branches = ['openwrt', 'lede', 'immortalwrt', 'Lienol'];
              const docker_imgs = ['1911086027/openwrt_cortex-a53:openwrt', '1911086027/openwrt_cortex-a53:lede', '1911086027/openwrt_cortex-a53:immortalwrt', '1911086027/openwrt_cortex-a53:Lienol'];

              for (let i = 0; i < 4; i++) {
                const source_branch = source_branches[i];
                const docker_img = docker_imgs[i];
                
                const { data } = await octokit.rest.actions.createWorkflowDispatch({
                  owner: '1911086027',
                  repo: 'OpenWrt_Built',
                  workflow_id: 'update-checker.yml',
                  ref: 'main',
                  inputs: {
                    source_branch: source_branch,
                    openwrt_board: 's905d',
                    openwrt_kernel: '5.10.y_5.15.y',
                    docker_img: docker_img,
                  }
                });
                
                console.log(`Workflow dispatch for ${source_branch} with Docker image ${docker_img} completed.`);
              }
            }
            run();