#
# https://github.com/P3TERX/Actions-OpenWrt
#
# File: .github/workflows/update-checker.yml
# Description: Source code update checker
#
# Copyright (c) 2019-2024 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#

name: Update Checker

on:
  workflow_dispatch:
    inputs:
      source_branch:
        description: "Select source branch"
        required: true
        default: "immortalwrt"
        type: choice
        options:
          - openwrt
          - lede
          - immortalwrt
          - Lienol
      openwrt_board:
        description: "Select device board"
        required: true
        default: "s905d"
        type: choice
        options:
          - all
          #Cortex-A53
          - s905d
          - rk3328
          - h6
      openwrt_kernel:
        description: "Select kernel version"
        required: true
        default: "5.10.y_5.15.y"
        type: choice
        options:
          - 5.4.y
          - 5.10.y
          - 5.15.y
          - 6.1.y
          - 6.6.y
          - 5.10.y_5.15.y
          - 6.1.y_6.6.y
      docker_img:
        description: "Set the docker image"
        required: false
        default: "1911086027/openwrt_cortex-a53:immortalwrt"
        type: choice
        options:
          - 1911086027/openwrt_cortex-a53:openwrt
          - 1911086027/openwrt_cortex-a53:lede
          - 1911086027/openwrt_cortex-a53:immortalwrt
          - 1911086027/openwrt_cortex-a53:Lienol
jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Get Commit Hash
      id: getHash
      run: |
        if [[ "${{ github.event.inputs.source_branch }}" == *"openwrt"* ]]; then
            REPO_URL="https://github.com/openwrt/openwrt"
            REPO_BRANCH="openwrt-23.05"
        elif [[ "${{ github.event.inputs.source_branch }}" == *"lede"* ]]; then
            REPO_URL="https://github.com/coolsnowwolf/lede"
            REPO_BRANCH="master"
        elif [[ "${{ github.event.inputs.source_branch }}" == *"immortalwrt"* ]]; then
            REPO_URL="https://github.com/immortalwrt/immortalwrt"
            REPO_BRANCH="openwrt-23.05"

        elif [[ "${{ github.event.inputs.source_branch }}" == *"Lienol"* ]]; then
            REPO_URL="https://github.com/Lienol/openwrt"
            REPO_BRANCH="23.05"
        else
            echo "Unknown source code repository."
            exit 1
        fi
        git clone -q --single-branch --depth=1 --branch=${REPO_BRANCH} ${REPO_URL}
        echo "commitHash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

    - name: Compare Commit Hash
      id: cacheHash
      uses: actions/cache@v4
      with:
        path: .commitHash
        key: commitHash_${{ steps.getHash.outputs.commitHash }}

    - name: Save New Commit Hash
      if: steps.cacheHash.outputs.cache-hit != 'true'
      run: |
        echo ${{ steps.getHash.outputs.commitHash }} | tee .commitHash
        
  call-workflow:
#    if: check.steps.cacheHash.outputs.cache-hit != 'true'
    uses: ./.github/workflows/openwrt-builder.yml
    with:
        source_branch: ${{ github.event.inputs.source_branch }}
        openwrt_board: ${{ github.event.inputs.openwrt_board }}
        openwrt_kernel: ${{ github.event.inputs.openwrt_kernel }}
        docker_img: ${{ github.event.inputs.docker_img }}
